version: '3'

volumes:
  postgres_data:
    driver: local
  db_data:

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    volumes:
      - ./:/etl/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - db
  backend:  
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./src/:/code/src:ro
    ports:
      - '8000:80'
    env_file:
      - .env
    depends_on:
      - keycloak
      - db
  thingsboard:
    image: thingsboard/tb-postgres
    ports:
      - 9090:9090
      - 1883:1883
      - 7070:7070
      - 5683-5688:5683-5688/udp
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
    environment:
      - SYS_ADMIN_USERNAME=sysadmin@thingsboard.org
      - SYS_ADMIN_PWD=sysadmin
      - TENANT_ADMIN_USERNAME=tenant@thingsboard.org
      - TENANT_ADMIN_PWD=tenant
      - CUSTOMER_USER_USERNAME=customer@thingsboard.org
      - CUSTOMER_USER_PWD=customer
    restart: always
    tty: true
    depends_on:
      - backend
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      command:
        - start-dev
      depends_on:
        - postgres