version: '3'

volumes:
  postgres_data:
    driver: local
  db_data:

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    volumes:
      - ./:/etl/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - db
  backend:  
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./src/:/code/src:ro
    ports:
      - '8000:80'
    env_file:
      - .env
    depends_on:
      - keycloak
      - db

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      command:
        - start-dev
      depends_on:
        - postgres